### ISSUE TITLE
I dump a ar9462 card (5bwb222) from 0xf7d00000 but mmap failed?

### ISSUE THREAD

**Issue by youxiaojie** [rsa9000/atheepmgr#1]
I dump a ar9462 card (5bwb222) from 0xf7d00000 but mmap failed?

aet also this error.

root@debian:/media/allan/home_data/atheepmgr# ./atheepmgr -M f7d00000 save ar9462.bin
conmem: mmap of device at 0xf7d00000 for 0x00010000 bytes failed: Operation not permitted

**Comment by rsa9000** [comment]
The Linux kernel in Debian does not allow mapping of an arbitrary memory regions, even for the root user. This is due to the Linux kernel configuration. So, access to the hardware from the userspace is impossible with the default Debian kernel.

You can disable these restrictive options and recompile the kernel. Then, after fetching the dump from the NIC, you can return the default kernel back. Once I had to do it. And it helped.

**Comment by youxiaojie** [comment]
Thanks. 
Another question, when I remove the iron cap of the wifi card, I could not see any physical chips like 24c32(eeprom) where is it? my card have vid:pid like 168c:abcd  something got wrong, so I want to see whether eeprom is good.

**Comment by rsa9000** [comment]
AR94xx chips have a small internal storage called OTP since this storage block is OneTime Programmed. So if you do not see any EEPROM chip on the PCB then the card vendor decide to use OTP to store card settings.

atheepmgr will check EEPROM first and if there are no data then it will check OTP memory.

**Comment by youxiaojie** [comment]
The Linux kernel in Debian does not allow mapping of an arbitrary memory regions, even for the root user. This is due to the Linux kernel configuration. So, access to the hardware from the userspace is impossible with the default Debian kernel.

You can disable these restrictive options and recompile the kernel. Then, after fetching the dump from the NIC, you can return the default kernel back. Once I had to do it. And it helped.

which option I should set when make menuconfig？

**Comment by rsa9000** [comment]
> which option I should set when make menuconfig

You need to *disable* STRICT_DEVMEM option. In the menuconfig it located at the following path "Kernel Hacking" -> "Filter access to /dev/mem"
