### ISSUE TITLE
ath9280 unsupported?

### ISSUE THREAD

**Issue by lgbaldoni** [rsa9000/atheepmgr#3]
I own a Compex WLE200NX card for which I would like to permanently change the regulatory domain. Thing is, I don't know where to start. I understand I will have to rebuild the kernel (I'm on debian), but then what?

Thanks

**Comment by rsa9000** [comment]
AR9280 chip is perfectly supported, at least printing of its EEPROM contents.

There is another issue. Overwriting regdomain with an arbitrary value can lead to card operation out of permitted bands in your place. That is why I did not implement the regdomain overwrite option for any of the supported layouts. That was a bad news.

The good news is that it is easly to implement the such option. Just a 5-10 lines of code. But be aware about your local laws and keep card conforming to them. Nearest radar or a commercial radio network will not be happy to hear another one transmitter :)

If your card has a broken regdomain value and you plan to use it in a wireless router, then I suggest to use OpenWrt firmware since it have a special patch intended to workaround broken regdomains.

**Comment by rsa9000** [comment]
I close the issue. Feel free to reopen it if need it.
