### ISSUE TITLE
Parameter list would be nice

### ISSUE THREAD

**Issue by grepwood** [rsa9000/atheepmgr#8]
I'm trying to update RegDomain1 on an AR5416 card and for the life of me I can't figure out what's the parameter name that atheepmgr expects. I know that in the EEPROM dump it's RegDomain1 in the base header.

So, I think it's fair to say that if the software could dump a parameter list for the specified map, that would enable users like myself to know which parameter it is they want to update.

**Comment by rsa9000** [comment]
Hi @grepwood,

there is already one at your wish :) As stated next to the *-h* option: "Use -v option to see more details", so just run the utility like this to see a lot more info:

```
user@host $ ./atheepmgr -vh
```

But I would like to say sorry, since the RegDomain rewriting is not supported and likely will not be. More details are here https://github.com/rsa9000/atheepmgr/issues/5#issuecomment-1421088831.

**Comment by grepwood** [comment]
Thank you @rsa9000 !

FWIW, my need to change the domain is that it currently works as a card from Armenia:
```
[   23.355269] ath: EEPROM regdomain: 0x30
[   23.355304] ath: EEPROM indicates we should expect a direct regpair map
[   23.355313] ath: Country alpha2 being used: AM
[   23.355320] ath: Regpair used: 0x30
[   23.366151] ieee80211 phy0: Atheros AR5416 MAC/BB Rev:2 AR2133 RF Rev:81 mem=0xf7fb0000, irq=18
```

I'm located in Poland, not Armenia, and this is causing this card to basically not support most wifi networks around me.
